/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/spotify/(spotify)': RouteRecordInfo<'/spotify/(spotify)', '/spotify', Record<never, never>, Record<never, never>>,
    '/spotify/callback': RouteRecordInfo<'/spotify/callback', '/spotify/callback', Record<never, never>, Record<never, never>>,
    '/spotify/playlists': RouteRecordInfo<'/spotify/playlists', '/spotify/playlists', Record<never, never>, Record<never, never>>,
    '/spotify/playlists/[id]': RouteRecordInfo<'/spotify/playlists/[id]', '/spotify/playlists/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tidal/': RouteRecordInfo<'/tidal/', '/tidal', Record<never, never>, Record<never, never>>,
    '/tidal/callback': RouteRecordInfo<'/tidal/callback', '/tidal/callback', Record<never, never>, Record<never, never>>,
  }
}
